return {
    {
        'Mofiqul/vscode.nvim',
        lazy = false,
        priority = 1000,
        config = function()
            vim.o.background = 'dark'
            require('vscode').setup({
                style = 'dark',
                transparent = false,
                italic_comments = false,
                underline_links = true,
                terminal_colors = true,
                -- Match vscode-default-dark-plus.json (Dark+)
                color_overrides = {
                    -- Editor
                    vscFront = '#D4D4D4',
                    vscBack = '#1E1E1E',
                    vscTabCurrent = '#1E1E1E',
                    vscSelection = '#264F78',
                    vscLineNumber = '#858585',
                    vscContext = '#404040',
                    vscContextCurrent = '#707070',
                    -- Syntax (Dark+ tokenColors)
                    vscGray = '#808080',
                    vscViolet = '#646695',
                    vscBlue = '#569CD6',
                    vscAccentBlue = '#4FC1FF',
                    vscLightBlue = '#9CDCFE',
                    vscGreen = '#6A9955',
                    vscBlueGreen = '#4EC9B0',
                    vscLightGreen = '#B5CEA8',
                    vscRed = '#F44747',
                    vscOrange = '#CE9178',
                    vscLightRed = '#D16969',
                    vscYellowOrange = '#D7BA7D',
                    vscYellow = '#DCDCAA',
                    vscPink = '#C586C0',
                },
                group_overrides = {
                    Normal = { fg = '#D4D4D4', bg = '#1E1E1E' },
                    Visual = { bg = '#264F78' },
                    VisualNOS = { bg = '#3A3D41' },
                    CursorLine = { bg = '#2A2D2E' },
                    ColorColumn = { bg = '#2A2D2E' },
                    LineNr = { fg = '#858585', bg = '#1E1E1E' },
                    CursorLineNr = { fg = '#C6C6C6', bg = '#1E1E1E' },
                    SignColumn = { bg = '#1E1E1E' },
                    Search = { bg = '#613315' },
                    IncSearch = { bg = '#515c6a' },
                    MatchParen = { bg = '#51504F', bold = true },
                    Whitespace = { fg = '#404040' },
                    NonText = { fg = '#404040' },
                    IndentBlanklineChar = { fg = '#404040' },
                    IndentBlanklineContextChar = { fg = '#707070' },
                    IblIndent = { fg = '#404040' },
                    IblScope = { fg = '#707070' },
                    -- Treesitter / syntax aligned to Dark+ scopes
                    Comment = { fg = '#6A9955' },
                    ['@comment'] = { fg = '#6A9955' },
                    String = { fg = '#CE9178' },
                    ['@string'] = { fg = '#CE9178' },
                    ['@string.regexp'] = { fg = '#D16969' },
                    Number = { fg = '#B5CEA8' },
                    ['@number'] = { fg = '#B5CEA8' },
                    Boolean = { fg = '#569CD6' },
                    ['@boolean'] = { fg = '#569CD6' },
                    Constant = { fg = '#569CD6' },
                    ['@constant'] = { fg = '#4FC1FF' },
                    ['@constant.builtin'] = { fg = '#569CD6' },
                    Function = { fg = '#DCDCAA' },
                    ['@function'] = { fg = '#DCDCAA' },
                    ['@function.builtin'] = { fg = '#DCDCAA' },
                    ['@function.method'] = { fg = '#DCDCAA' },
                    Identifier = { fg = '#9CDCFE' },
                    ['@variable'] = { fg = '#9CDCFE' },
                    ['@variable.parameter'] = { fg = '#9CDCFE' },
                    ['@variable.member'] = { fg = '#9CDCFE' },
                    ['@property'] = { fg = '#9CDCFE' },
                    ['@variable.builtin'] = { fg = '#569CD6' },
                    Type = { fg = '#4EC9B0' },
                    ['@type'] = { fg = '#4EC9B0' },
                    ['@type.builtin'] = { fg = '#4EC9B0' },
                    Structure = { fg = '#4EC9B0' },
                    Keyword = { fg = '#569CD6' },
                    ['@keyword'] = { fg = '#569CD6' },
                    ['@keyword.function'] = { fg = '#569CD6' },
                    ['@keyword.operator'] = { fg = '#569CD6' },
                    ['@keyword.conditional'] = { fg = '#C586C0' },
                    ['@keyword.repeat'] = { fg = '#C586C0' },
                    ['@keyword.return'] = { fg = '#C586C0' },
                    ['@keyword.exception'] = { fg = '#C586C0' },
                    ['@keyword.import'] = { fg = '#C586C0' },
                    Conditional = { fg = '#C586C0' },
                    Repeat = { fg = '#C586C0' },
                    Statement = { fg = '#C586C0' },
                    Operator = { fg = '#D4D4D4' },
                    ['@operator'] = { fg = '#D4D4D4' },
                    ['@tag'] = { fg = '#569CD6' },
                    ['@tag.attribute'] = { fg = '#9CDCFE' },
                    ['@tag.delimiter'] = { fg = '#808080' },
                    ['@punctuation.bracket'] = { fg = '#D4D4D4' },
                    ['@punctuation.delimiter'] = { fg = '#D4D4D4' },
                    PreProc = { fg = '#569CD6' },
                    Include = { fg = '#C586C0' },
                    StorageClass = { fg = '#569CD6' },
                    Special = { fg = '#D7BA7D' },
                    ['@character.special'] = { fg = '#D7BA7D' },
                    Error = { fg = '#F44747' },
                    ['@error'] = { fg = '#F44747' },
                    DiagnosticError = { fg = '#F44747' },
                    DiagnosticWarn = { fg = '#DCDCAA' },
                    DiagnosticInfo = { fg = '#569CD6' },
                    DiagnosticHint = { fg = '#4EC9B0' },
                },
            })
            vim.cmd.colorscheme('vscode')
        end,
    },
    {
        'numToStr/Comment.nvim',
        config = function()
            require('Comment').setup()
        end,
    },
    {
        "OXY2DEV/markview.nvim",
        lazy = false,
    },
    {
        "tris203/precognition.nvim",
        lazy = false,
        opts = {
            startVisible = true,
            targetedMotionHints = { enabled = false },
        },
    },
    -- {
    --     "m4xshen/hardtime.nvim",
    --     lazy = false,
    --     dependencies = { "MunifTanjim/nui.nvim" },
    --     opts = {},
    -- },
}
